export default {
    listName: [
        'Contextual Email Capture',
    ],
    contextualEmailSessionCookieName: 'oz__cec',
    cookieExpirationInDays: 1/2,  // 12 hours
    templates: [
        // Q2 LO-23
        {
            templateId: 1,
            timeDelayInSeconds: 15,
            intro: {
                title: 'Time to upgrade your life!',
                message: 'Would you rather...',
            },
            tag: 'Travel',
            sweepstakeTagType: '$oz_sweepstake_primary-category',
            targetPage: 'Product',
            sweepstakeState: 'active',
            startDate: '2020-09-09',
            endDate: '2020-09-30',
            options: [
                {
                    optionId: 1,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_HomeReno_1.jpg',
                        alt: '',
                        caption: 'Completely renovate your home',
                    },
                    formTitle: 'Make home sweeter!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'sign up',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Home Reno',
                    legalCopy: 'By completing this form you\'re signing up to receive our home renovation emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
                {
                    optionId: 2,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_100K_1.jpg',
                        alt: '',
                        caption: 'Live large with $100,000',
                    },
                    formTitle: 'Cash in on that dream!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'sign up',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Financial Freedom',
                    legalCopy: 'By completing this form you\'re signing up to receive our financial freedom emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
            ],
        },
        // Q3 LO-24
        {
            templateId: 2,
            timeDelayInSeconds: 4,
            intro: {
                title: 'Since you\'re here...',
                message: 'What\'s your ideal road trip car?',
            },
            tag: 'Cars',
            sweepstakeTagType: '$oz_sweepstake_primary-category',
            targetPage: 'Product',
            sweepstakeState: 'closed',
            startDate: '2020-09-09',
            endDate: '2020-09-30',
            options: [
                {
                    optionId: 1,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_AdventureCar_5.jpg',
                        alt: '',
                        caption: 'The one that can handle anything',
                    },
                    formTitle: 'Let\'s make it happen!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get access',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Adventure Cars',
                    legalCopy: 'By completing this form you\'re signing up to receive our adventure car emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
                {
                    optionId: 2,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_ElectricCar_2.jpg',
                        alt: '',
                        caption: 'The one that helps the environment',
                    },
                    formTitle: 'Let\'s make it happen!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get access',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Electric Cars',
                    legalCopy: 'By completing this form you\'re signing up to receive our electric car emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
            ],
        },
        // Q4 LO-121
        {
            templateId: 3,
            timeDelayInSeconds: 4,
            intro: {
                title: 'Next up...',
                message: 'Choose your ideal vacation!',
            },
            tag: 'Cars',
            sweepstakeTagType: '$oz_sweepstake_primary-category',
            targetPage: 'Thank You',
            sweepstakeState: 'active',
            startDate: '2020-10-14',
            endDate: '2020-11-04',
            options: [
                {
                    optionId: 1,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_AdventureTravel_1.jpg',
                        alt: '',
                        caption: 'Full of adventure & epic experiences.',
                    },
                    formTitle: 'Go chase that dream!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get on the list',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Adventure Travel',
                    legalCopy: 'By completing this form you\'re signing up to receive our adventure travel emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
                {
                    optionId: 2,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_CultureTravel_3.jpg',
                        alt: '',
                        caption: 'All about the food! Travel by tastebuds.',
                    },
                    formTitle: 'Go chase that dream!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get on the list',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Food',
                    legalCopy: 'By completing this form you\'re signing up to receive our food travel emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
            ],
        },
        // Q1 LO-22
        {
            templateId: 4,
            timeDelayInSeconds: 4,
            intro: {
                title: 'When you\'re on a road trip...',
                message: 'Which kind of car do you prefer?',
            },
            tag: 'Travel',
            sweepstakeTagType: '$oz_sweepstake_primary-category',
            targetPage: 'Thank You',
            sweepstakeState: 'active',
            startDate: '2020-10-14',
            endDate: '2020-11-04',
            options: [
                {
                    optionId: 1,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_AdventureCar_8.jpg',
                        alt: '',
                        caption: 'The one that can handle anything',
                    },
                    formTitle: 'Let\'s make it happen!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get on the list',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Adventure Cars',
                    legalCopy: 'By completing this form you\'re signing up to receive our adventure car emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
                {
                    optionId: 2,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_ElectricCar_1.jpg',
                        alt: '',
                        caption: 'The one that helps the environment',
                    },
                    formTitle: 'Let\'s make it happen!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get on the list',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Electric Cars',
                    legalCopy: 'By completing this form you\'re signing up to receive our electric car emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
            ],
        },
        // Q6 LO-122
        {
            templateId: 5,
            timeDelayInSeconds: 4,
            intro: {
                title: 'Want another life upgrade?',
                message: 'Choose your dream car!',
            },
            tag: 'best-life',
            sweepstakeTagType: '$oz_sweepstake_primary-category',
            targetPage: 'Thank You',
            sweepstakeState: 'active',
            startDate: '2020-10-14',
            endDate: '2020-11-04',
            options: [
                {
                    optionId: 1,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_AdventureCar_7.jpg',
                        alt: '',
                        caption: 'One that can handle anything',
                    },
                    formTitle: 'Let\'s make it happen!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'sign up',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Adventure Cars',
                    legalCopy: 'By completing this form you\'re signing up to receive our adventure car emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
                {
                    optionId: 2,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_ElectricCar_4.jpg',
                        alt: '',
                        caption: 'One that helps the environment',
                    },
                    formTitle: 'Let\'s make it happen!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'sign up',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Electric Cars',
                    legalCopy: 'By completing this form you\'re signing up to receive our electric car emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
            ],
        },
        // Q5 LO-123
        {
            templateId: 6,
            timeDelayInSeconds: 4,
            intro: {
                title: 'Dreaming of a vacation?',
                message: 'Choose your ideal getaway!',
            },
            tag: 'Travel',
            sweepstakeTagType: '$oz_sweepstake_primary-category',
            targetPage: 'Product',
            sweepstakeState: 'closed',
            startDate: '2020-10-14',
            endDate: '2020-11-04',
            options: [
                {
                    optionId: 1,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_IslandTravel_1.jpg',
                        alt: '',
                        caption: 'Soaking up the sun on the beach',
                    },
                    formTitle: 'Make that dream come true!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get access',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Travel',
                    legalCopy: 'By completing this form you\'re signing up to receive our travel emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
                {
                    optionId: 2,
                    image: {
                        src: '//images.omaze.com/web/assets/images/static/features/email-capture/HandRaiser_Q320_LuxuryTravel_1.jpg',
                        alt: '',
                        caption: 'Luxury, 5-star, first-class everything',
                    },
                    formTitle: 'Make that dream come true!',
                    formMessage: 'Sign up to score special offers.',
                    ctaLabel: 'get access',
                    successTitle: 'We\'ve got you!',
                    successMessage: 'Keep an eye on your inbox to learn more.',
                    listName: 'Handraisers Travel',
                    legalCopy: 'By completing this form you\'re signing up to receive our travel emails. No pressure—you can unsubscribe at any time.',
                    legalUrl: '',
                },
            ],
        },
    ],
}
