name: 00 (Auto) Pull Request Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [integration]
    paths-ignore:
    - ".github/**"
    - ".githooks/**"
    - "**.md"

  issue_comment:
    types: [created]

env:
  CI: true

jobs:
  test:
    if: |
      (startsWith(github.event.comment.body, '/test'))
      || (github.event_name == 'pull_request')
    runs-on: [ubuntu-18.04]
    steps:
      - name: Git checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Setup .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.RELEASE_WORKFLOW_TOKEN }}" > ~/.npmrc

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        id: deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run unit tests
        id: test
        run: npm run test
