name: 04 (Dispatch) Promote Release Candidate

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to promote'     
        required: true

jobs:
  promote-RC-tag:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Git checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/release
          token: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}
          fetch-depth: 0

      - name: promote release
        id: promotion
        env:
          GIT_AUTHOR_NAME: omaze-cicd
          GIT_AUTHOR_EMAIL: info@omaze.com
          GIT_COMMITTER_NAME: omaze-cicd
          GIT_COMMITTER_EMAIL: info@omaze.com
        run: |
          git merge refs/tags/${{github.event.inputs.tag}}
          git push
